require("plugins")
require("nvim_formatter")
require("keymaps")
-- require('coc')
require("settings")
-- require('lsp.lua-ls')
require("colorscheme")
require("airline")
require("completion")
require("devicons")
require("nvim_lsp")
require("gitsign")
require("nvim_telescope")
require("nvim_rooter")
require("nvim_treesitter")
