vim.cmd 'let g:airline#extensions#tabline#enabled = 1'
vim.cmd 'let g:airline#extensions#tabline#left_sep = \' \''
vim.cmd 'let g:airline#extensions#tabline#left_alt_sep = \' \''
vim.cmd 'let g:airline#extensions#tabline#formatter = \'default\''
vim.cmd 'let g:airline_powerline_fonts = 1'
vim.cmd 'let g:airline_theme = \'onedark\''
